apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: debezium-capturer-binding
spec:
  subject:
    apiVersion: apps/v1
    kind: Deployment
    selector:
      matchLabels:
        debezium.io/component: DebeziumServer
        debezium.io/instance: my-debezium
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: debezium-sample-broker
---
apiVersion: debezium.io/v1alpha1
kind: DebeziumServer
metadata:
  name: my-debezium
spec:
  image: quay.io/debezium/server:jcechace
  quarkus:
    config:
      log.level: DEBUG
      log.console.json: false
      kubernetes-config.enabled: true
      kubernetes-config.secrets: postgresql-credentials
  runtime:
    metrics:
      jmxExporter:
        enabled: true
  sink:
    type: http
  format:
    value:
      type: cloudevents
  source:
    class: io.debezium.connector.postgresql.PostgresConnector
    offset:
      memory: {}
    schemaHistory:
      memory: {}
    config:
      database.hostname: postgresql
      database.port: 5432
      database.user: ${POSTGRES_USER}
      database.password: ${POSTGRES_PASSWORD}
      database.dbname: ${POSTGRES_DB}
      topic.prefix: cdc
      table.include.list: inventory.votes
      batch.size: 1
      plugin.name: pgoutput